agent:
  cache_ttl: 300
  connection_pool_size: 50
  enable_caching: true
  max_iterations: 10
  request_timeout: 30
openrouter:
  api_key: "YOUR KEY"
  base_url: https://openrouter.ai/api/v1
  model: qwen/qwen-turbo
orchestrator:
  aggregation_strategy: consensus
  backoff_factor: 2
  enable_rate_limiting: true
  max_concurrent_requests: 4
  parallel_agents: 4
  question_generation_prompt:
    'You are an orchestrator that needs to create {num_agents}
    different questions to thoroughly analyze this topic from multiple angles.


    Original user query: {user_input}


    Generate exactly {num_agents} different, specific questions that will help gather
    comprehensive information about this topic.

    Each question should approach the topic from a different angle (research, analysis,
    verification, alternatives, etc.).


    Return your response as a JSON array of strings, like this:

    ["question 1", "question 2", "question 3", "question 4"]


    Only return the JSON array, nothing else.

    '
  retry_attempts: 3
  synthesis_prompt:
    "You have {num_responses} different AI agents that analyzed the\
    \ same query from different perspectives. \nYour job is to synthesize their responses\
    \ into ONE comprehensive final answer.\n\nHere are all the agent responses:\n\n\
    {agent_responses}\n\nIMPORTANT: Just synthesize these into ONE final comprehensive\
    \ answer that combines the best information from all agents. \nDo NOT call mark_task_complete\
    \ or any other tools. Do NOT mention that you are synthesizing multiple responses.\
    \ \nSimply provide the final synthesized answer directly as your response.\n"
  task_timeout: 300
search:
  max_results: 5
  user_agent: Mozilla/5.0 (compatible; OpenRouter Agent)
system_prompt:
  "You are a helpful research assistant. When users ask questions that\
  \ require \ncurrent information or web search, use the search tool and all other\
  \ tools available to find relevant \ninformation and provide comprehensive answers\
  \ based on the results.\n\nIMPORTANT: When you have fully satisfied the user's request\
  \ and provided a complete answer, \nyou MUST call the mark_task_complete tool with\
  \ a summary of what was accomplished and \na final message for the user. This signals\
  \ that the task is finished.\n"
